/**
 * Measured evidence, generated by scripts/collect_evidence.mjs.
 *
 * Nothing here is hand-written prose. If the suite is red, or the deviation changes, the
 * numbers the UI renders change with it — re-run the script before quoting any of them.
 */
import generated from './evidence.generated.json';

export interface Evidence {
  generatedAt: string;
  generatedBy: string;
  tests: { total: number; passed: number; files: number; command: string };
  wetBulbValidation: {
    hoursChecked: number;
    cities: number;
    meanAbsDeviationC: number;
    maxAbsDeviationC: number;
    reference: string;
    scope: string;
  };
}

export const EVIDENCE = generated as Evidence;

export function evidenceAgeHours(now: Date = new Date()): number {
  const generatedAt = new Date(EVIDENCE.generatedAt);
  return Math.round(((now.getTime() - generatedAt.getTime()) / 3_600_000) * 10) / 10;
}
